# Generated by Django 3.0 on 2020-02-11 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagination', '0003_example'),
    ]

    operations = [
        migrations.RenameField(
            model_name='example',
            old_name='data1',
            new_name='iteration',
        ),
        migrations.RenameField(
            model_name='example',
            old_name='data2',
            new_name='pid',
        ),
        migrations.AddField(
            model_name='example',
            name='randint',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
